### ISSUE TITLE
ClassNotFoundException at runtime when using JDK7

### ISSUE THREAD

**Issue by konomae** [yatatsu/AutoBundle#10]
If building my app with JDK7, no compilation errors but the app crashes at runtime.

> java.lang.ClassNotFoundException: Didn't find class "com.example.App"

When I switch to JDK8, the app runs correctly.

> /Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home

to

> /Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home

Is it possible that this project supports JDK7?
Or just should I upgrade JDK8?

Similar info: https://github.com/requery/requery/issues/76

**Comment by yatatsu** [comment]
@konomae, yes, the processor in this library only works in JDK8. 

At this time, it works in JDK7 because there are no use of new API such as `Stream`.
But I'm not going to support JDK7 without sufficient reason. 

I recommend you to upgrade JDK8. If you have to use JDK7, you can fork it!

**Comment by konomae** [comment]
Thanks!

Currently, there is no reason to use JDK7 for my project.
So, I will upgrade to JDK8.
