### ISSUE TITLE
Create Bundle

### ISSUE THREAD

**Issue by Ztiany** [yatatsu/AutoBundle#20]
Sometimes, I do not need to initialize the Fragment directly, but need a Bundle instance.

![image](https://cloud.githubusercontent.com/assets/8726426/21174296/34bee97a-c217-11e6-80a7-67aa44b0f10b.png)

**Comment by yatatsu** [comment]
@Ztiany Sorry, AutoBundle does not support instantiation of Bundle without Fragment instance. 
If it is a feature request, would you tell me more detail about that use case?

**Comment by yatatsu** [comment]
Fixed in `4.0.0`, use `bundle()`.

https://github.com/yatatsu/AutoBundle/releases/tag/4.0.0
