### ISSUE TITLE
Library module support

### ISSUE THREAD

**Issue by Piasy** [yatatsu/AutoBundle#27]
Currently if I use auto-bundle both at library module and app module, there will be multiple `AutoBundleBindingDispathcer`, which will cause the build fail:

```
Error:Execution failed for task ':app:transformClassesWithJarMergingForDevDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: 
duplicate entry: com/yatatsu/autobundle/AutoBundleBindingDispatcher.class
```

FragmentArgs support library module, but when using it in library module, we need to call the fragment-specific builder's `injectArguments` method, call `FragmentArgs.inject` doesn't work, that's not a bad idea, could auto-bundle add this feature too?

**Comment by yatatsu** [comment]
Thanks your feedback! 
Yes, you're right, now cannot use at multi modules. 
Annotation processor options (like FragmentArgs) is most simple solution. 
But as you pointed out, you need specific helper to bind (e.g. `FooFragmentAutoBundle.bind(this)`).

**Comment by Piasy** [comment]
Yep, but at least it's better. Can we add this feature?

**Comment by yatatsu** [comment]
Another solution is following.

First, in library project modules,

```groovy
android {
    defaultConfig {
        javaCompileOptions {
            annotationProcessorOptions {
                className 'com.yatatsu.autobundle.processor.AutoBundleProcessor'
                arguments = [ autoBundleAsLibrary : 'com.example.library' ]
            }
        }
    }
}
```

and in app's build gradle,

```groovy
android {
    defaultConfig {
        javaCompileOptions {
            annotationProcessorOptions {
                className 'com.yatatsu.autobundle.processor.AutoBundleProcessor'
                arguments = [ subDispatchers : 'com.example.library.AutoBundleBindingDispatcher' ]
            }
        }
    }
}
```

the code generated would be...

```java
public final class AutoBundleBindingDispatcher {
  final com.example.library.AutoBundleBindingDispatcher subDispatcher1 = new AutoBundleBindingDispatcher()
  public void bind(@NonNull Object target, @NonNull Bundle args) {
    if (target instanceof ExampleActivity) {
      ExampleActivityAutoBundle.bind((ExampleActivity)target, args);
      return;
    // bind by library's dispatcher
    subDispatcher1.bind(target, args);
  }
}
```

What do you think this? Is it too much option?

**Comment by Piasy** [comment]
That's cool, and it's one time configuration, totally ok, IMO.

**Comment by yatatsu** [comment]
Thanks, I will do it in a few days.

**Comment by yatatsu** [comment]
Now released 4.1.0, library module is supported!
Please Follow [README#use-in-library-module](https://github.com/yatatsu/AutoBundle#use-in-library-module), try it.

**Comment by Piasy** [comment]
Thats awesome! Thanks!

**Comment by shingohu** [comment]
if use this way,but dagger2 can not use ？？

**Comment by yatatsu** [comment]
I don't try with dagger2, but it may work. If you have problem, please report it.

**Comment by shingohu** [comment]
@yatatsu yes，I am use dagger2 and this library in library module, if I set
  javaCompileOptions {
            annotationProcessorOptions {
                className 'com.yatatsu.autobundle.processor.AutoBundleProcessor'
                arguments = [ autoBundleAsLibrary : 'com.example.library' ]
            }
        }

but can not compile dagger2, I think is not you library problem，but I dont Know how to do

**Comment by yatatsu** [comment]
@shingohu I got it. Maybe DSL is wrong.

https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.AnnotationProcessorOptions.html

Try this.

```
javaCompileOptions {
annotationProcessorOptions {
arguments = [ autoBundleAsLibrary : 'com.example.library' ]
}
}
```

I will fix README. Thanks!

**Comment by yatatsu** [comment]
I updated README!

**Comment by shingohu** [comment]
Thanks！😁😁
