### ISSUE TITLE
AndroidX Support

### ISSUE THREAD

**Issue by tobiasrohloff** [yatatsu/AutoBundle#30]
This library is unfortunately not usable with [AndroidX](https://developer.android.com/topic/libraries/support-library/androidx-overview), mainly because some annotation imports like `android.support.annotation.NonNull` cannot be found anymore with the new namespaces for the generated classes.

**Comment by yatatsu** [comment]
Sorry for late reply. I will try it in a few days.

**Comment by yatatsu** [comment]
@tobiasrohloff 
We release the version 5.0.2. It includes AndroidX. Thanks!

**Comment by tobiasrohloff** [comment]
Works great, thank you!
