### ISSUE TITLE
Avoid reflection

### ISSUE THREAD

**Issue by yatatsu** [yatatsu/AutoBundle#6]
`AutoBundle.bind(Activity)` is easy interface. It lookups dispatcher class internally.
For this interface, AutoBundle use reflection at first time(only one time).
But even if one time, should avoid reflection.
Should use `FooActivityAutobundle.bind(Activity)` instead above.

**Comment by Piasy** [comment]
Without reflection, there are lots of boilerplate code to write in every activity and fragment, maybe the overhead of the one time reflection invoke worth the code convenience.

**Comment by yatatsu** [comment]
@Piasy , Thanks for your feedback! 
I understand what you said. But it seems not to be redundant so much. 
`AutoBundle.bind(this, bundle)` to `FooActivityAutoBundle.bind(this, bundle)`, isn't it? I think it is not enough to worth to use reflection.

**Comment by yatatsu** [comment]
In #9 , Revive dispatcher class without reflection.

**Comment by Piasy** [comment]
Creative solution! 👏
